//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calcOptimalZRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_NSI_Pech
    {
        public int PechId { get; set; }
        public string Name { get; set; }
        public bool actual { get; set; }
    }
}
