//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calcOptimalZRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class testReportEntities : DbContext
    {
        public testReportEntities()
            : base("name=testReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DC_NSI_Pech> DC_NSI_Pech { get; set; }
    
        public virtual int OptShihtDC_HimZolaKoks_Load(Nullable<System.DateTime> dt, Nullable<byte> debug)
        {
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            var debugParameter = debug.HasValue ?
                new ObjectParameter("debug", debug) :
                new ObjectParameter("debug", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OptShihtDC_HimZolaKoks_Load", dtParameter, debugParameter);
        }
    
        public virtual ObjectResult<OptShihtDC_Param_Load_Result> OptShihtDC_Param_Load(Nullable<System.DateTime> dt, Nullable<byte> debug)
        {
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            var debugParameter = debug.HasValue ?
                new ObjectParameter("debug", debug) :
                new ObjectParameter("debug", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OptShihtDC_Param_Load_Result>("OptShihtDC_Param_Load", dtParameter, debugParameter);
        }
    
        public virtual ObjectResult<OptShihtDC_Shihta_Load_Result> OptShihtDC_Shihta_Load(Nullable<System.DateTime> dtFirstDay, Nullable<byte> nPech, Nullable<short> matType, Nullable<byte> debug)
        {
            var dtFirstDayParameter = dtFirstDay.HasValue ?
                new ObjectParameter("dtFirstDay", dtFirstDay) :
                new ObjectParameter("dtFirstDay", typeof(System.DateTime));
    
            var nPechParameter = nPech.HasValue ?
                new ObjectParameter("NPech", nPech) :
                new ObjectParameter("NPech", typeof(byte));
    
            var matTypeParameter = matType.HasValue ?
                new ObjectParameter("MatType", matType) :
                new ObjectParameter("MatType", typeof(short));
    
            var debugParameter = debug.HasValue ?
                new ObjectParameter("debug", debug) :
                new ObjectParameter("debug", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OptShihtDC_Shihta_Load_Result>("OptShihtDC_Shihta_Load", dtFirstDayParameter, nPechParameter, matTypeParameter, debugParameter);
        }
    }
}
